platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node 8 x64
  - npm install cnpm@7.1.0 -g --registry=https://registry.npm.taobao.org
  - cnpm install

build_script:
  - npm run dist

test: off

branches:
  only:
    - master

